In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [16]:
#define the vocabulary size
voc_size=10000

In [17]:
#one hote representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3060, 3410, 997, 7092],
 [3060, 3410, 997, 8391],
 [3060, 6563, 997, 5581],
 [4352, 4795, 8150, 3459, 6955],
 [4352, 4795, 8150, 3459, 3798],
 [4429, 3060, 9050, 997, 3016],
 [9884, 303, 3171, 3459]]

In [24]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [25]:
import numpy as np

In [26]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3060 3410  997 7092]
 [   0    0    0    0 3060 3410  997 8391]
 [   0    0    0    0 3060 6563  997 5581]
 [   0    0    0 4352 4795 8150 3459 6955]
 [   0    0    0 4352 4795 8150 3459 3798]
 [   0    0    0 4429 3060 9050  997 3016]
 [   0    0    0    0 9884  303 3171 3459]]


In [27]:
# feature representation
dim=10

In [29]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 147ms/step


array([[[ 0.00664035,  0.01162745, -0.02064281,  0.00723916,
          0.03362025,  0.02370495, -0.03355231,  0.0472559 ,
         -0.02273335,  0.02807888],
        [ 0.00664035,  0.01162745, -0.02064281,  0.00723916,
          0.03362025,  0.02370495, -0.03355231,  0.0472559 ,
         -0.02273335,  0.02807888],
        [ 0.00664035,  0.01162745, -0.02064281,  0.00723916,
          0.03362025,  0.02370495, -0.03355231,  0.0472559 ,
         -0.02273335,  0.02807888],
        [ 0.00664035,  0.01162745, -0.02064281,  0.00723916,
          0.03362025,  0.02370495, -0.03355231,  0.0472559 ,
         -0.02273335,  0.02807888],
        [ 0.04466811,  0.01079547, -0.00032966,  0.02689464,
          0.02894907, -0.03426006, -0.00365063, -0.0434349 ,
         -0.04748256, -0.01262782],
        [-0.04848984,  0.03081265,  0.00928444, -0.00420846,
          0.00568626,  0.04246285,  0.01761801,  0.01866691,
         -0.03672606, -0.04972221],
        [-0.03734589,  0.01791132,  0.01263788,  0.0